---
title: "Components and Methods"
output:
  distill::distill_article:
    toc: TRUE
    theme: theme.css
---

## Understanding Afterschool Programs in Dallas County
[Introduce the concept of supply and demand as individual components and how they can help identify gaps in Dallas County.]
Dallas Afterschool Programs by Census Tract

```{r, map of DAS afterschool programs in county, echo = FALSE, message=FALSE, warning=FALSE, layout="l-body", fig.height=8}
# Generate Jenks Breaks for plot
brks_das <- BAMMtools::getJenksBreaks(dasmetrics$ProgSqMi, k = 6)
dasmetrics$group <- cut(dasmetrics$ProgSqMi,
                             breaks = brks_das,
                       include.lowest = TRUE)
labs_das <- round(brks_das)

# Generate labels based on Jenks breaks for plot
labs_plot <- paste0("(", labs_das[1:5], " - ", labs_das[2:6], ")")

# Generate Plot
ggplot() +
  geom_sf(data = dasmetrics, aes(fill = group), color = "#595959") +
  geom_sf(data = dallasCounty, color = "#323232", fill = NA, size = 2) +
  geom_sf(data = highways, color = "#323232", size = 1) +
  scale_fill_brewer(name = "",
                    palette = "BuPu",
                    label = labs_plot,
                    guide = guide_legend(direction = "horizontal",
                                         nrow = 1,
                                         label.position = "top")) +
  labs(title = "After School Program Density (per Square Mile)",
       #subtitle = "U.S. Census Bureau, American Community Survey 5-Year Estimates 2020",
       x = "",
       y = "",
       color = "") +
  theme_void() +
  theme(legend.position = "bottom",
        legend.key.width = unit(0.5, units = "in"),
        plot.caption = element_text(size = 36, face = "italic"),
        legend.spacing = unit(0, "in"), 
        legend.key.height = unit(0.25, "in"), 
        legend.spacing.x = unit(0.1, "in"), 
        legend.justification = "center",
        legend.margin=margin(4,4,4,4),
        legend.box.spacing = margin(0.5))

```

## Existing Afterschool Environment

[Describe metrics included in Existing Afterschool Environment and reasons for their inclusion]

### Summary of Current Programs

```{r, table of programs, echo = FALSE, message=FALSE, warning=FALSE, layout="l-body-outset", fig.height=8}
das <- das_programs %>%
  st_drop_geometry(.) %>%
  group_by(facility_type) %>%
  dplyr::summarise(count = n(),
                   capacity = sum(max_capacity)) %>%
  mutate(#source = "Dallas Afterschool",
         avgseats = round(capacity/count),
         percap = capacity/sum(capacity),
         percapStr = paste0(round(percap*100, digits = 1), "%"),
         facility_type = ifelse(facility_type == "", "Not Available", facility_type))

#hhs <- hhs_programs %>%
#  st_drop_geometry(.) %>%
#  dplyr::summarise(count = n(),
#                   capacity = sum(capacity)) %>%
#  mutate(source = "Texas Health and Human Services",
#         avgseats = round(capacity/count))
#
#cacfp <- cacfp_programs %>%
#  st_drop_geometry(.) %>%
#  dplyr::summarise(count = n(),
#                   capacity = sum(site_license_capacity, na.rm = TRUE)) %>%
#  mutate(source = "Child and Adult Food Care Program",
#         avgseats = round(capacity/count))

das %>%
  select(-percap) %>%
  knitr::kable(.,
               col.names = c('Facility Type', 'Total Programs', 'Seat Capacity', 'Average Seats', 'Percent of Seats')) %>%
  kable_styling()
```

```{r, Supply Scores Histogram, echo = FALSE, message=FALSE, warning=FALSE}
das %>%
  ggplot(aes(x = percap, y = reorder(facility_type, -percap), fill = facility_type)) +
  geom_bar(stat = "identity", alpha = 0.7) +
  scale_x_continuous(labels = scales::percent) +
  scale_color_manual(values = CPALtools::pal_cpalfac) +
  scale_fill_manual(values = CPALtools::pal_cpalfac) +
  labs(title = "Percentage of Total Seats by Facility Type",
       #subtitle = "U.S. Census Bureau, American Community Survey 5-Year Estimates 2020",
       x = "",
       y = "",
       color = "") +
  theme_bw() +
  theme(legend.position = "none",
        legend.key.width = unit(0.5, units = "in"),
        plot.caption = element_text(size = 36, face = "italic"),
        legend.spacing = unit(0, "in"), 
        legend.key.height = unit(0.25, "in"), 
        legend.spacing.x = unit(0.1, "in"), 
        legend.justification = "center",
        legend.margin=margin(4,4,4,4),
        legend.box.spacing = margin(0.5))
```


### Programs in Dallas County

```{r, map of programs in dallas county, echo = FALSE, message=FALSE, warning=FALSE, layout="l-body", fig.height=8}
#unique(das_programs$facility_type)
ccc <- das_programs %>%
  filter(facility_type == "Child Care Center")
school <- das_programs %>%
  filter(facility_type == "School")
missing <- das_programs %>%
  filter(facility_type == "")
comcen <- das_programs %>%
  filter(facility_type == "Community Center/Nonprofit")
faith <- das_programs %>%
  filter(facility_type == "Faith Community")
munbui <- das_programs %>%
  filter(facility_type == "Municipal Building")
aptcom <- das_programs %>%
  filter(facility_type == "Apartment Complex")

leaflet() %>%
#  setView(lng = -96.7970, lat = 32.7767, zoom = 10) %>%
  addTiles(urlTemplate = cpal_mapbox, attribution = cpal_leaflet) %>%
    addCircleMarkers(data = ccc,
                     stroke = FALSE,
                     radius = 4,
                     fillColor = "#0089C4",
                     weight = 1,
                     fillOpacity = 1,
                     group = "Child Care Center"
              ) %>%
    addCircleMarkers(data = school,
                     stroke = FALSE,
                     radius = 4,
                     fillColor = "#DC5034",
                     weight = 1,
                     fillOpacity = 1,
                     group = "School"
              ) %>%
    addCircleMarkers(data = missing,
                     stroke = FALSE,
                     radius = 4,
                     fillColor = "#54494B",
                     weight = 1,
                     fillOpacity = 1,
                     group = "Not Available"
              ) %>%
    addCircleMarkers(data = comcen,
                     stroke = FALSE,
                     radius = 4,
                     fillColor = "#FFB533",
                     weight = 1,
                     fillOpacity = 1,
                     group = "Non-Profit"
              ) %>%
    addCircleMarkers(data = faith,
                     stroke = FALSE,
                     radius = 4,
                     fillColor = "#87F1FF",
                     weight = 1,
                     fillOpacity = 1,
                     group = "Faith Community"
              ) %>%
    addCircleMarkers(data = munbui,
                     stroke = FALSE,
                     radius = 4,
                     fillColor = "#ADB533",
                     weight = 1,
                     fillOpacity = 1,
                     group = "Municipal Building"
              ) %>%
    addCircleMarkers(data = aptcom,
                     stroke = FALSE,
                     radius = 4,
                     fillColor = "#8078B6",
                     weight = 1,
                     fillOpacity = 1,
                     group = "Apartment Complex"
              ) %>%
  addPolygons(data = dallasCounty,
              color = "#686158",
              weight = 3,
              smoothFactor = 0.2, 
              fillOpacity = 0,
              group = "Dallas County"
              ) %>%
  addLayersControl(
    baseGroups = c("Dallas County"),
    overlayGroups = c("Apartment Complex", "Child Care Center", "Faith Community", "Municipal Building", "Non-Profit", "School", "Not Available"),
    position = "topright",
    options = layersControlOptions(collapsed = FALSE))

```
## Current Neighborhood Conditions

[Describe metrics included in Current Neighborhood Conditions and reasons for their inclusion]

### Expected Population

```{r, Eligible Population, echo = FALSE, message=FALSE, warning=FALSE}
dasmetrics %>%
  ggplot(aes(x = eligPop)) +
  geom_histogram(bins = 50, color = "#DC5034", fill = "#DC5034", alpha = 0.7) +
  labs(title = "Distribution of Eligible Population (5 - 14)",
       #subtitle = "U.S. Census Bureau, American Community Survey 5-Year Estimates 2020",
       x = "",
       y = "",
       color = "") +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.key.width = unit(0.5, units = "in"),
        plot.caption = element_text(size = 36, face = "italic"),
        legend.spacing = unit(0, "in"), 
        legend.key.height = unit(0.25, "in"), 
        legend.spacing.x = unit(0.1, "in"), 
        legend.justification = "center",
        legend.margin=margin(4,4,4,4),
        legend.box.spacing = margin(0.5))
```

[Summary of population variables for Dallas County. How many families/children do we expect could go to Afterschool programs in the county?]
[Specific family types (Single-mother households, households below poverty, etc.)]

## Methodology 

[Basic description of methodology and reason for use of components]