---
title: "Priority Areas"
output:
  distill::distill_article:
    toc: TRUE
    theme: theme.css
---

```{r Set-Up Block, include = FALSE}
#load libraries
library(tidyverse)
library(sf)
library(leaflet)
library(mapboxapi)
library(htmltools)
library(CPALtools)

# import Dallas County Boundary
dallasCounty <- st_read("data/dallasCounty.geojson") %>%
  st_transform(crs = 4269)

# import Dallas City Council Boundary
dallascouncil <- st_read("data/citycouncil.geojson") %>%
  st_transform(crs = 4269)

# import component index metrics
dasComponents <- st_read("data/dasComponents.geojson")  %>%
  st_transform(crs = 4269) %>%
  mutate(IndexGroup = ifelse(DesertBrks == "[ -58, -34 ]", "Extreme Need", 
                             ifelse(DesertBrks ==  "(-34,-11]", "High Need", 
                                    ifelse(DesertBrks ==  "(-11,15]", "Moderate Need", 
                                           ifelse(DesertBrks == "(15,50]", "Moderate Excess", 
                                                  ifelse(DesertBrks == "(50,98]", "High Excess", 
                                                         ifelse(is.na(DesertBrks), NA, "ERROR")))))))
unique(dasComponents$DesertBrks)
unique(dasComponents$IndexGroup)

#split groups into multiple dataframes
desert_en <- dasComponents %>%
  filter(IndexGroup == "Extreme Need")
desert_hn <- dasComponents %>%
  filter(IndexGroup == "High Need")
desert_mn <- dasComponents %>%
  filter(IndexGroup == "Moderate Need")
desert_me <- dasComponents %>%
  filter(IndexGroup == "Moderate Excess")
desert_he <- dasComponents %>%
  filter(IndexGroup == "High Excess")

# import ACS variables
acsmetrics <- st_read("data/ACS Demographic Metrics.geojson")

# import calculated metrics 
das_metrics <- st_read("data/Calculated Tract Metrics.geojson") %>%
  st_transform(crs = 4269) %>%
  left_join(., st_drop_geometry(dasComponents)) %>%
  left_join(., st_drop_geometry(acsmetrics))

# generate table by group
names(das_metrics)
typologytable <- das_metrics %>%
  st_drop_geometry(.) %>%
  group_by(IndexGroup) %>%
  summarise(TotalTracts = n(),
            AreaSqMi = sum(AreaSqMi),
            eligPop = sum(eligPop),
            #cpr = sum(bp_u18E, na.rm = TRUE)/sum(pop_u18E, na.rm = TRUE),
            #bp_u18 = sum(bp_u18E, na.rm = TRUE),
            dasPrograms = sum(dasPrograms),
            dasSeats = sum(dasSeats),
            cacfpPrograms = sum(cacfpPrograms),
            cacfpSeats = sum(cacfpSeats),
            hhsPrograms = sum(hhsPrograms),
            hhsSeats = sum(hhsSeats),
            totPrograms = sum(dasPrograms+cacfpPrograms+hhsPrograms),
            totSeats = sum(dasSeats+cacfpSeats+hhsSeats)) %>%
  mutate(poppro = round(eligPop/totSeats, digits = 3)) %>%
  select(-(cacfpPrograms:hhsSeats))
```
## Typology of Program Access

[Description of (Demand-Supply) HIGH-HIGH, HIGH-LOW, LOW-HIGH, LOW-LOW demand in afterschool programs]
```{r, Typology Table}
typologytable
```
[ggplot2 scatterplot and table visualizing each typology and counts of tracts.]
```{r Typology Leaflet Map, echo = FALSE, message=FALSE, warning=FALSE, layout="l-page", fig.height=8}
leaflet() %>%
#  setView(lng = -96.7970, lat = 32.7767, zoom = 10) %>%
  addTiles(urlTemplate = cpal_mapbox, attribution = cpal_leaflet) %>%
  addPolygons(data = desert_en,
              fillColor = "red",
              weight = 1,
              opacity = 1,
              color = "red",
              fillOpacity = 0.7,
              group = "Extreme Need"
              ) %>%
    addPolygons(data = desert_hn,
              fillColor = "orange",
              weight = 1,
              opacity = 1,
              color = "orange",
              fillOpacity = 0.7,
              group = "High Need"
              ) %>%
  addPolygons(data = desert_mn,
              fillColor = "yellow",
              weight = 1,
              opacity = 1,
              color = "yellow",
              fillOpacity = 0.7,
              group = "Moderate Need"
              ) %>%
  addPolygons(data = desert_me,
              fillColor = "green",
              weight = 1,
              opacity = 1,
              color = "green",
              fillOpacity = 0.7,
              group = "Moderate Excess"
              ) %>%
  addPolygons(data = desert_he,
              fillColor = "blue",
              weight = 1,
              opacity = 1,
              color = "blue",
              fillOpacity = 0.7,
              group = "High Excess"
              ) %>%
  addPolygons(data = dallasCounty,
              color = "#686158",
              weight = 3,
              smoothFactor = 0.2, 
              fillOpacity = 0,
              group = "Dallas County"
              ) %>%
  addPolygons(data = dallascouncil,
              color = "#686158",
              weight = 3,
              smoothFactor = 0.2, 
              fillOpacity = 0,
              group = "Dallas City Council"
              ) %>%

  addLayersControl(
    baseGroups = c("Dallas County"),
    overlayGroups = c("Extreme Need", "High Need", "Moderate Need", "Moderate Excess", "High Excess", "Dallas City Council"),
    position = "topright",
    options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup("High Need") %>%
  hideGroup("Moderate Need") %>%
  hideGroup("Moderate Excess") %>%
  hideGroup("High Excess") %>%
  hideGroup("Dallas City Council")
```
## Characteristics of LOW-HIGH

[Summaries of the demographics of LOW-HIGH group]

[Leaflet map displaying LOW-HIGH census tracts.]

## Recommendations for LOW-HIGH

[List of recommendations for LOW-HIGH typology]

## Insights on Other Typologies

[Any additional important insight for other typology groups, maybe unnecessary.]