---
title: "Supply and Demand Index"
output:
  distill::distill_article:
    toc: TRUE
    theme: theme.css
---

## Topline results

## Supply and Demand in Dallas County
```{r, Supply Scores Histogram, echo = FALSE, message=FALSE, warning=FALSE}
dasComponents %>%
  ggplot(aes(x = indexSupply)) +
  geom_histogram(bins = 50, color = "#0089C4", fill = "#0089C4", alpha = 0.7) +
  labs(title = "Distribution of Supply Scores",
       #subtitle = "U.S. Census Bureau, American Community Survey 5-Year Estimates 2020",
       x = "",
       y = "",
       color = "") +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.key.width = unit(0.5, units = "in"),
        plot.caption = element_text(size = 36, face = "italic"),
        legend.spacing = unit(0, "in"), 
        legend.key.height = unit(0.25, "in"), 
        legend.spacing.x = unit(0.1, "in"), 
        legend.justification = "center",
        legend.margin=margin(4,4,4,4),
        legend.box.spacing = margin(0.5))
```

```{r, Demand Scores Histogram, echo = FALSE, message=FALSE, warning=FALSE}
dasComponents %>%
  ggplot(aes(x = indexDemand)) +
  geom_histogram(bins = 50, color = "#DC5034", fill = "#DC5034", alpha = 0.7) +
  labs(title = "Distribution of Demand Scores",
       #subtitle = "U.S. Census Bureau, American Community Survey 5-Year Estimates 2020",
       x = "",
       y = "",
       color = "") +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.key.width = unit(0.5, units = "in"),
        plot.caption = element_text(size = 36, face = "italic"),
        legend.spacing = unit(0, "in"), 
        legend.key.height = unit(0.25, "in"), 
        legend.spacing.x = unit(0.1, "in"), 
        legend.justification = "center",
        legend.margin=margin(4,4,4,4),
        legend.box.spacing = margin(0.5))
```


```{r, Component Index, echo = FALSE, message=FALSE, warning=FALSE, layout="l-page", fig.height=8}
#names(dasDemo)
popup <- paste0("<b>", "GEOID: ", "</b>", dasDemo$GEOID, "<br>",
               "<b>", "Median Household Income: ", "</b>", "$", dasDemo$mhiE, "<br>",
               "<b>", "Total Population: ", "</b>", dasDemo$tot_popE, "<br>",
               "<b>", "Asian (%): ", "</b>", round(dasDemo$as_per*100, digits =1), "%", "<br>",
               "<b>", "Black (%): ", "</b>", round(dasDemo$bl_per*100, digits =1), "%", "<br>",
               "<b>", "Hispanic (%) : ", "</b>", round(dasDemo$hi_per*100, digits =1), "%", "<br>",
               "<b>", "White (%): ", "</b>", round(dasDemo$wh_per*100, digits =1), "%", "<br>",
               "<b>", "Child Poverty Rate (u18): ", "</b>", round(dasDemo$cpr*100, digits =1), "%", "<br>",
               "<b>", "Internet Access (%): ", "</b>", round(dasDemo$int_per*100, digits =1), "%", "<br>",
               "<b>", "Single-Mother Households (%): ", "</b>", round(dasDemo$smhh_per*100, digits =1), "%", "<br>",
               "<b>", "Single-Mother Households Below Poverty (%): ", "</b>", round(dasDemo$smhh_bpE*100, digits =1), "%", "<br>",
               "<b>", "Unemployment Rate: ", "</b>", round(dasDemo$unemE*100, digits =1), "%"
               )

brksSupply <- BAMMtools::getJenksBreaks(dasComponents$indexSupply, k = 6)
brksDemand <- BAMMtools::getJenksBreaks(dasComponents$indexDemand, k = 6)

palSupply <- colorBin("BuPu", domain = dasComponents$indexSupply, bins = brksSupply)
palDemand <- colorBin("RdPu", domain = dasComponents$indexDemand, bins = brksDemand)

leaflet() %>%
#  setView(lng = -96.7970, lat = 32.7767, zoom = 10) %>%
  addTiles(urlTemplate = cpal_mapbox, attribution = cpal_leaflet) %>%
  addPolygons(data = dasComponents,
              fillColor = ~palDemand(indexDemand),
              weight = 1,
              opacity = 1,
              color = ~palDemand(indexDemand),#"#686158",
              #dashArray = "3",
              fillOpacity = 0.6,
              group = "Demand Score",
              popup = ~popup
              ) %>%
  addPolygons(data = dasComponents,
              fillColor = ~palSupply(indexSupply),
              weight = 1,
              opacity = 1,
              color = ~palSupply(indexSupply), #"#686158",
              #dashArray = "3",
              fillOpacity = 0.6,
              group = "Supply Score",
              popup = ~popup
              ) %>%
  addPolygons(data = dallasCounty,
              color = "#686158",
              weight = 3,
              smoothFactor = 0.2, 
              fillOpacity = 0,
              group = "Dallas County"
              ) %>%
  addPolygons(data = highways,
              color = "#686158",
              weight = 2,
              smoothFactor = 0.2, 
              fillOpacity = 0,
              group = "Dallas County"
              ) %>%
  addLegend(data = dasComponents,
            "bottomright", 
            pal = palDemand, 
            values = ~indexDemand,
            title = "Demand Score",
            group = "Demand Score",
            #labFormat = labelFormat(prefix = "$"),
            opacity = 1) %>%
  addLegend(data = dasComponents,
            "bottomright", 
            pal = palSupply, 
            values = ~indexSupply,
            title = "Supply Score",
            group = "Supply Score",
            #labFormat = labelFormat(prefix = "$"),
            opacity = 1) %>%
  addLayersControl(
    overlayGroups = c("Demand Score", "Supply Score"),
    baseGroups = c("Dallas County"),
    position = "topright",
    options = layersControlOptions(collapsed = FALSE)) %>% 
  hideGroup("Demand Score")
```

## Afterschool Program Access
[Summaries and charts detailing the analysis and the types of people affected by low program supply.]